---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "dada2"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "conda-forge::r-base"
  - "conda-forge::r-essentials"
  - "conda-forge::r-tidyverse"
  - "conda-forge::r-data.table"
  - "bioconda::bioconductor-dada2"
  - "bioconda::bioconductor-shortread"

